### PR TITLE
Feature tags

### PR DESCRIPTION
**Pull request by maxstrebel**
- Adds tags
- Use tag-group for multiple tags in a group
- I had to import quite a lot variables just to be able to assign the body font size. We should discuss how to handle this in the future. Import all?

```
<div class="tag-group">
  <a href="#" class="tag">Tag</a>
</div>
```

### CODE REVIEW

**Comment by rsmdt** [comment]
As a general thought, it would be better to have custom stuff separated. Can we do the following:

1. Move `_tags.scss` into `custom/_tags.scss`
2. `@import "custom/tags";` inside `_custom.scss`
3. Add description to the newly added component so it is viewable in the generated documentation

**Comment by jayhof** [comment]
I moved the tags component into a custom folder and added some rudimentary documentation which describes tags as well as tag-groups.

**Review by jayhof — COMMENTED** [review]
Developing with the bootstrap documentation felt really nice, i'm happy with the workflow now.

I also don't like the excessive use of variables in custom.scss which we don't overwrite but need for the mapping. I don't have another solution though for now it's fine and we should add the variable blocks as needed.

**Comment by maxstrebel** [comment]
That's great. I'll keep looking for a solution for custom.scss. @rudionrails thx for the good idea.
I'll port the stuff from the boilerplate asap.

**Pull request merged**
