### PR TITLE
[DR-7755] adds sections

### PR DESCRIPTION
**Pull request by jayhof**
Ports "sections" to the joblocal bootstrap theme, adds some documentation as a sections page under "layout".

There's still some todos open, @maxstrebel would be great if you contribute here.

### CODE REVIEW

**Comment by jayhof** [comment]
@tim-steinberg good stuff, now @maxstrebel can take over again!

**Comment by jayhof** [comment]
@maxstrebel the sections background variants need more work e.g. the "bg-contrast" doesn't exist, if you have a look in scss/utilities/_background.scss this is where bootstrap creates the bg variants, we'd have to add our own "bg-contrast" or could we used the provided "bg-faded"?

**Comment by maxstrebel** [comment]
@jayhof I'll look into this after cards. I like the wording, but beforehand we should have a look how the bs-class is intended to be used. If it fits the context, we should use it.

**Comment by maxstrebel** [comment]
@jayhof lets use bg-faded for now.

**Review by maxstrebel — APPROVED** [review]
I added the styles for the headings with utility classes. 

For the sake of speed and ease I think we should use these and have a more thorough discussion afterwards about the pros and cons.

**Comment by jayhof** [comment]
I removed the custom bg colors as we now make use of the bg-... utilities, I also streamlined the docs page to more closely reflect a default bootstrap component doc page.

**Pull request merged**
