### PR TITLE
Feature/slider

### PR DESCRIPTION
**Pull request by maxstrebel**
Adds Slick Slider. I tried to document it as good as time let me.

Here are some things to note:
- Slider arrows are now added by svg in variables. So no more ties to a char. Positioning, though, should be adjusted in the future.
- .btn-rounded will be revisited in a branch to tie this correctly to padding vars, etc.
- Styles and Docs do not yet respect the fact, that this will be in a section and controls need to be adjusted to their respective background colors. This should be done asap after implementation.
- grid spacing and row spacing are now solved with 2 helpers. This way we can use the slider as we wish. The Image Slideshow (on company page) will introduce different spacing and variables.

### CODE REVIEW

**Review by tim-steinberg — APPROVED** [review]
Just a small thing i have noticed: When the Next/Prev Buttons are in :active-state the arrow disappears. Apart from that the slider feels very good. Thx Max.

**Comment by maxstrebel** [comment]
Hi @tim-steinberg, thanks for noticing and the nice feedback! I just fixed the issues, could you have another look? Thx Tim :)

**Comment by tim-steinberg** [comment]
👍 Looks good now.

**Comment by maxstrebel** [comment]
Perfect, thx!

**Pull request merged**
