### PR TITLE
Feature/dr 7752 navbar style

### PR DESCRIPTION
**Pull request by tim-steinberg**
Hey @maxstrebel,

this is my first suggestion of the nav.
I'm struggling to get the two navs side by side. How would you do it?
What I also don't understand is that i have to do a `@import "../mixins/hover";` in the custom nav scss to have the `@include hover-focus` available. Jay didn't had to do it in the dropdown.

Thx for your help.

### CODE REVIEW

**Comment by maxstrebel** [comment]
Hi @tim-steinberg, concerning the mixins, these should work, I had no time to review it but maybe you ask Jay. Since the dropdown merge these should be working.

Concerning the navs:
If you want them to display next to each other, you need a wrapper class, for example .navbar. This must be set to display flex and the containing navs need a flex attribute (flex: 1). From this moment on, they display next to each other. Next, it might be needed to solve the display of the nav-items so they don't fill up all the space they have, but only the space they need. You can, again use flexbox for that. Here is a simple mockup for that:

```
<!-- This makes two navbars work -->
<div class="navbar" style="display: flex;">
  <div class="nav" style="flex: 1;">
    <!-- Nav -->
  </div>
  <div class="nav" style="flex: 1;">
    <!-- Nav -->
  </div>
</div>

<!-- Align one to the right -->
<div class="navbar" style="display: flex;">
  <div class="nav" style="flex: 1;">
    <!-- Nav -->
  </div>
  <div class="nav" style="flex: 1; justify-content: flex-end;">
    <!-- Nav Right justified -->
  </div>
</div>

<!-- Align one to the right -->
<ul class="nav" style="flex: 1; display: flex; /* This display flex is for the items */">
  <li class="nav-item" style="flex: 0">Item</li>
  <li class="nav-item" style="flex: 0">Item</li>
  <li class="nav-item" style="flex: 0">Item</li>
  <li class="nav-item" style="flex: 0">Item</li>
</ul>
```

**Comment by tim-steinberg** [comment]
Hi @maxstrebel,
thx for your input. This works.
If i would use the `navbar`-class for this, i would overwrite some bootstrap behavior which i would think is not so cool. Or what do you think?
Maybe I just create a `nav-container` class?

About the mixins: Jay and I already had a look. But we couldn't find the bug. I will leave like this for now.

**Comment by maxstrebel** [comment]
Hi @tim-steinberg,
sure, I was not proposing to overwrite it, just wanted to tell we need a wrapper class – I'll have a look which one this could be. Let's have a look later on with Rudi, how to handle this case.

Concerning the bug, I'll keep an eye open. Tomorrow I will continue to port the missing parts, for example the cards and will look if this problem occurs again.

**Comment by tim-steinberg** [comment]
Hey @maxstrebel,
i have edited the pull-request and made the modifications now to the navbar-inverse.
I would add the padding to 0 in the component style as we don't want this on all toolbars. Or do you have an other suggestion?

**Comment by maxstrebel** [comment]
Hey @tim-steinberg I'll have a look right after I finished the cards.

**Comment by maxstrebel** [comment]
@tim-steinberg I just made some minor adjustments to the component. I gave a navbar-sm class to separate this change from the general navbar size.

To clear the padding, for now I'd recommend to follow @rudionrails idea to use the p-0 class for this, as I decided to use these for our spacing. I will talk to jay about this and document its usage in one of the next pull-requests. What do you think?

**Comment by tim-steinberg** [comment]
@maxstrebel Great, thanks for the navbar-sm class. I will use the p-0 class in the component to align the padding.

**Pull request merged**
